Update 09-functions.yaml

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -2,7 +2,7 @@ name: 09 - Using Functions
 
 
 on:
-  pull_request:
+  # pull_request:
   workflow_dispatch:
 
 jobs:
@@ -24,17 +24,17 @@ jobs:
         if: ${{ failure() && !cancelled() && contains(github.event.pull_request.title, 'fix') }}
         run: echo "I am a bug fix"
 
-      - name: Sleep for 20 seconds
-        run: sleep 20
+      # - name: Sleep for 20 seconds
+      #   run: sleep 20
       
-      - name: Failing step
-        run: exit 1
+      # - name: Failing step
+      #   run: exit 1
 
-      - name: I will be skipped
+      - name: I will be executed
         if: ${{ success() }}
         run: echo "I will print if previous steps succeed."
 
-      - name: I will execute
+      - name: I will not be execute
         if: ${{ failure() }}
         run: echo "I will print if any previous step fails."
 
